### ISSUE TITLE
/motd command can't find Player ID and initiates backup or removal of old bakups

### ISSUE THREAD

**Issue by tbankstemp** [rexxar-tc/EssentialsPlugin#19]
The Below is also happening when a user joins with /motd or when typing in /motd.
Using ==
Extender  v1.109.13.56-alpha
# Essentials  v1.13.4.186-alpha

First this: 2015-11-30 21:26:35.1540|Info|Chat - Server: Unable to find player id

Then after a few seconds..
2015-11-30 21:19:47.4327|Info|Removed old backup: C:####\World_Location###\LogsOwned_Audit_11-15-2015_13-21.log
2015-11-30 21:19:47.4327|Error|System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean
throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkH
ost)
   at EssentialsPlugin.ProcessHandlers.ProcessBackup.CleanupBackups()
   at EssentialsPlugin.ProcessHandlers.ProcessBackup.Handle()
    |System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean
throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkH
ost)
   at EssentialsPlugin.ProcessHandlers.ProcessBackup.CleanupBackups()
   at EssentialsPlugin.ProcessHandlers.ProcessBackup.Handle()

**Comment by rexxar-tc** [comment]
That is really weird. For a little while, Essentials had a different naming scheme for backups, and threw that error when it tried to do a cleanup. Try manually deleting old backups, and it should go away. I have absolutely no idea how the motd could possibly trigger a backup cleanup, but it's happening.

**Comment by tbankstemp** [comment]
Okay, thanks for the quick response! :)  I just now noticed that it only happens on the first few (say 5 or 6) /motd commands issued. I did have some old backups in the directory, but had the server running earlier and it didn't remove them then. So that part could just be a fluke.

Thanks again.

**Comment by tbankstemp** [comment]
Any place I can donate for all your work on this?

**Comment by rexxar-tc** [comment]
If you really want to, you can do the paypal thing https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=ENXYXZVE6HS2C&lc=US&item_name=SESE%2fEssentials%20Development&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHosted (good gods that is an ugly link)

I'm gonna assume you got your problem fixed, so I'm closing this issue. You can still comment on it later if you want.

**Comment by tbankstemp** [comment]
Donated. Yes I believe the issue is resolved, but will report back after I do more testing today. Thanks again.
