### ISSUE TITLE
Server crash on load v1.13.6.198-alpha

### ISSUE THREAD

**Issue by zenduin** [rexxar-tc/EssentialsPlugin#41]
2016-06-02 11:48:44.947 - Thread:  28 ->  Exception occured: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at hkpConvexVerticesShape.new(UInt64 )
   at Havok.HkConvexVerticesShape.initShape(Vector3[] verts, Int32 count, Boolean shrink, Single convexRadius)
   at Havok.HkConvexVerticesShape..ctor(Vector3[] verts, Int32 count, Boolean shrink, Single convexRadius)
   at Sandbox.Game.Entities.Cube.MyCubeBlockCollector.AddConvexShape(MySlimBlock block, Boolean applySkeleton)
   at Sandbox.Game.Entities.Cube.MyCubeBlockCollector.CollectBlock(MySlimBlock block, MyPhysicsOption physicsOption, IDictionary`2 massResults, Boolean allowSegmentation)
   at Sandbox.Game.Entities.Cube.MyCubeBlockCollector.Collect(MyCubeGrid grid, MyVoxelSegmentation segmenter, MyVoxelSegmentationType segmentationType, IDictionary`2 massResults)
   at Sandbox.Game.Entities.Cube.MyGridShape..ctor(MyCubeGrid grid)
   at Sandbox.Game.Entities.Cube.MyGridPhysics.CreateBody()
   at Sandbox.Game.Entities.Cube.MyGridPhysics..ctor(MyCubeGrid grid, MyGridShape shape)
   at Sandbox.Game.Entities.MyCubeGrid.RebuildGrid()
   at Sandbox.Game.Entities.MyCubeGrid.InitInternal(MyObjectBuilder_EntityBase objectBuilder, Boolean rebuildGrid)
   at Sandbox.Game.Entities.MyEntities.InitEntity(MyObjectBuilder_EntityBase objectBuilder, MyEntity& entity)
   at Sandbox.ModAPI.MyEntitiesHelper_ModAPI.VRage.ModAPI.IMyEntities.CreateFromObjectBuilder(MyObjectBuilder_EntityBase objectBuilder)
   at EssentialsPlugin.EntityManagers.EntityManagement.RevealEntityObsolete(KeyValuePair`2 item)
   at EssentialsPlugin.EntityManagers.EntityManagement.CheckAndRevealEntitiesObsolete()
   at EssentialsPlugin.EntityManagers.EntityManagement.CheckAndRevealEntities()
   at EssentialsPlugin.ProcessHandlers.ProcessConceal.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass215_0.<PluginProcessing>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by rexxar-tc** [comment]
This is a Keen problem and has been reported many times in the forum.

**Comment by zenduin** [comment]
I posted this because the error only happens on THIS version of SESE essentials for me. When all I do is swap out the Essentials.dll for v1.134.06.179 there are no problems.
